### ISSUE TITLE
sco-id issue on Create SCO

### ISSUE THREAD

**Issue by Alpine91** [soheilrt/laravel-adobe-connect-client#3]
Client::scoCreate($scoInstance); method  throw blow exception

Soheilrt\AdobeConnectClient\Client\Exceptions\InvalidException: A required parameter sco-id is missing. in file C:\xampp7\htdocs\parandpardaz_lms\vendor\soheilrt\laravel-adobe-connect-client\src\Client\Helpers\StatusValidate.php on line 66

**Comment by soheilrt** [comment]
Could you add dump of your `$scoInstance` variable which causes this error!
